import { makeStartMarker, makeEndMarker, SECTION_DEFS } from "./markers";

export type WorkflowConfig = {
  sections: string[];
  schedule: string;
  baseUrl: string;
  themeName?: string;
  locale?: string;
  readmeFile?: string;
};

export const CRON_PRESETS = [
  { label: "Every hour",   value: "0 * * * *"    },
  { label: "Every 2 hrs",  value: "0 */2 * * *"  },
  { label: "Every 6 hrs",  value: "0 */6 * * *"  },
  { label: "Every 12 hrs", value: "0 */12 * * *" },
  { label: "Daily",        value: "0 0 * * *"    },
  { label: "Weekly",       value: "0 0 * * 1"    },
] as const;

function cronDesc(cron: string): string {
  const descMap: Record<string, string> = {
    "0 * * * *":    "every hour",
    "0 */2 * * *":  "every 2 hours",
    "0 */6 * * *":  "every 6 hours",
    "0 */12 * * *": "every 12 hours",
    "0 0 * * *":    "daily at midnight UTC",
    "0 0 * * 1":    "every Monday",
  };
  return descMap[cron] ?? cron;
}

export function generateWorkflowYaml(cfg: WorkflowConfig): string {
  const {
    sections,
    schedule,
    baseUrl,
    themeName = "github_dark",
    locale = "en",
    readmeFile = "README.md",
  } = cfg;

  const base = baseUrl.replace(/\/$/, "");

  // Build the fetch lines (one per section)
  const fetchLines = sections
    .map((id) => {
      const def = SECTION_DEFS[id];
      if (!def) return "";
      const url = `${base}${def.apiPath}?format=markdown&theme=${themeName}&locale=${locale}`;
      const envKey = `CONTENT_${id.toUpperCase().replace(/-/g, "_")}`;
      return `          ${envKey}="$(curl -sf '${url}' || echo 'FETCH_FAILED')"`;
    })
    .filter(Boolean)
    .join("\n");

  // Build the node inject script (one block per section)
  const injectBlocks = sections
    .map((id) => {
      const def = SECTION_DEFS[id];
      if (!def) return "";
      const envKey = `CONTENT_${id.toUpperCase().replace(/-/g, "_")}`;
      const sm = makeStartMarker(id);
      const em = makeEndMarker(id);
      // Escape for embedding inside a heredoc node script
      const smE = sm.replace(/'/g, "\\'");
      const emE = em.replace(/'/g, "\\'");
      return `
          // ── ${def.icon} ${def.label} ──────────────────────────────
          {
            const raw = process.env['${envKey}'] || '';
            if (!raw || raw === 'FETCH_FAILED') {
              warnings.push('[${id}] fetch failed — skipped');
            } else {
              const sm = '${smE}';
              const em = '${emE}';
              if (!readme.includes(sm) || !readme.includes(em)) {
                errors.push(
                  '[${id}] Missing markers in ${readmeFile}.\\n' +
                  '  Add: ${smE}\\n' +
                  '  And: ${emE}'
                );
              } else {
                const esc = s => s.replace(/[.*+?^\\\${}()|[\\]\\\\]/g, '\\\\$&');
                readme = readme.replace(
                  new RegExp(esc(sm) + '[\\\\s\\\\S]*?' + esc(em)),
                  sm + '\\n' + raw + '\\n' + em
                );
                updated++;
              }
            }
          }`;
    })
    .filter(Boolean)
    .join("\n");

  return `# ─────────────────────────────────────────────────────────────────────────────
# GitHub README Cards — Auto-Update Workflow
# Generated by: ${base}
# Sections : ${sections.join(", ")}
# Schedule : ${cronDesc(schedule)}
# ─────────────────────────────────────────────────────────────────────────────
name: "📊 Update README Cards"

on:
  schedule:
    - cron: "${schedule}"
  workflow_dispatch:
  push:
    branches: [main]
    paths: [".github/workflows/update-readme-cards.yml"]

jobs:
  update:
    name: "Fetch & inject card sections"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "⬇️ Checkout"
        uses: actions/checkout@v4
        with:
          token: \${{ secrets.GITHUB_TOKEN }}

      - name: "🌐 Fetch sections & inject into ${readmeFile}"
        shell: bash
        run: |
          # ── 1. Fetch each section ──────────────────────────────────────────
${fetchLines}

          # ── 2. Inject into README ──────────────────────────────────────────
          node << 'NODEJS'
          const fs = require('fs');
          let readme = fs.readFileSync('${readmeFile}', 'utf8');
          const errors   = [];
          const warnings = [];
          let updated = 0;
${injectBlocks}

          // ── 3. Write & report ──────────────────────────────────────────────
          fs.writeFileSync('${readmeFile}', readme);
          warnings.forEach(w => process.stderr.write('::warning::' + w + '\\n'));
          if (errors.length) {
            errors.forEach(e => process.stderr.write('::error::' + e + '\\n'));
            process.exit(1);
          }
          console.log('✅ Updated ' + updated + ' section(s) in ${readmeFile}');
          NODEJS
        env:
${sections
  .map((id) => {
    const envKey = `CONTENT_${id.toUpperCase().replace(/-/g, "_")}`;
    return `          ${envKey}: \${{ env.${envKey} }}`;
  })
  .join("\n")}

      - name: "💾 Commit if changed"
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name  "github-actions[bot]"
          git add ${readmeFile}
          if git diff --staged --quiet; then
            echo "ℹ️  No changes — nothing to commit"
          else
            git commit -m "chore(readme): auto-update cards [skip ci]"
            git push
            echo "✅ Pushed updated ${readmeFile}"
          fi
`;
}
